[package]
name = "macrocosm"
version = "0.1.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.86"
quote = { version = "1.0.36", default-features = false }
syn = { version = "2.0.68", default-features = false, features = ["full", "extra-traits", "printing"] }
